import { ResourceFeedback } from "@/components/resource-feedback";
import { PublicShell } from "@/components/public-site";
import { getPublicDocumentationGuide, publicDocumentationGuides } from "@/lib/public-documentation-guides";
import Link from "next/link";
import { notFound } from "next/navigation";
type PageProps={params:Promise<{slug:string}>};
export function generateStaticParams(){return publicDocumentationGuides.map(guide=>({slug:guide.slug}))}
export async function generateMetadata({params}:PageProps){const {slug}=await params;const guide=getPublicDocumentationGuide(slug);return {title:guide?`${guide.title} | Documentation`:"Documentation",description:guide?.summary,alternates:{canonical:`/documentation/${slug}`}}}
export default async function GuidePage({params}:PageProps){const {slug}=await params;const guide=getPublicDocumentationGuide(slug);if(!guide)notFound();return <PublicShell><article className="relative z-10 mx-auto max-w-4xl px-5 pb-24 pt-36"><nav className="text-sm text-slate-500"><Link className="hover:text-white" href="/documentation">Documentation</Link><span className="px-2">/</span><span>{guide.category}</span></nav><header className="mt-10 border-b border-white/10 pb-10"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-300">{guide.category}</p><h1 className="mt-4 font-outfit text-5xl font-semibold leading-tight md:text-7xl">{guide.title}</h1><p className="mt-6 text-xl leading-9 text-slate-400">{guide.summary}</p><p className="mt-5 font-mono text-xs text-slate-500">{guide.readTime}</p></header><p className="my-10 border-l-2 border-blue-300 pl-5 text-lg leading-8 text-slate-300">{guide.hero}</p><div className="space-y-12">{guide.sections.map(section=><section key={section.heading}><h2 className="font-outfit text-3xl font-semibold">{section.heading}</h2><div className="mt-5 space-y-4">{section.body.map(paragraph=><p key={paragraph} className="text-base leading-8 text-slate-400">{paragraph}</p>)}</div></section>)}</div><footer className="mt-14 border-t border-white/10 pt-8"><ResourceFeedback/></footer></article></PublicShell>}

